#-------------------------------------------------------------------------------
#  Copyright 2016 Honeywell International Inc. All rights reserved. 
#-------------------------------------------------------------------------------
# Verify that the transfer order number and the check digit can be scanned if 
# GetBarCode is used in the Protocol Translator voice attribute file.
# Scanned values are preceded by a '#' sign.
from BaseVDERPTestCase import BaseVDERPTestCase, EndOfApplication, BOTH_SERVERS #Needs to be first import
from main import main
import unittest

class test_barcode(BaseVDERPTestCase):

    def setUp(self):
        self.start_server(BOTH_SERVERS)
        self.clear()

    def test_barcode(self):
        #queue of LUT responses
        self.set_server_response('"ScreenID","PT-INIT-Integrated","","PT-INIT-Integrated","0","0","","http://10.201.94.23:8006/sap/vowm_lm01/","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","1","0","","say.ready.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","WelcomePrompt","","","1","1","","","welcome.message","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","OperatorPrompt","",".operator","1","2","","","current.operator.message","continue.say.ready3.message","","","","","","","0","0","0","1","1","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","2","0","","say.password.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"PassThrough","sap-user","sap-user",".operatorId","2","1","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"PassThrough","sap-client","sap-client","800","2","2","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"PassThrough","sap-language","sap-language",".languageCode","2","3","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"GetNumeric","sap-Password","sap-Password","","2","4","","","password.prompt","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SignOn","SignOn","","","2","5","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","RLMENU888-1","","RLMENU888-1","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTI4MDE3LjAwMi4wMS4wMQ==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PMLGF","~OKCode","/NEX","0","2","vreserve002.sign.off","","","","","","","correct.message","F8 LOff","","0","0","1","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","1","0","","function.number.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","TEXT1","~OKCode","1","1","1","","","","","","","","","1.main.voc.menu                      >","","0","0","0","0","0","1","0","0","","0"\r\n'
                                 '"Button","TEXT2","~OKCode","2","1","2","","","","","","","","","2.main.voc.menu                      >","","0","0","0","0","0","1","0","0","","0"\r\n'
                                 '"Button","TEXT3","~OKCode","3","1","3","","","","","","","","","3.main.voc.menu                      >","","0","0","0","0","0","1","0","0","","0"\r\n'
                                 '"GetNumeric","RLMOB-MENOPT","rlmob-menopt[1]","","1","8","","","function.prompt","","","","","","","RLMOB-PNEXT","0","0","0","0","0","0","1","1","","0"\r\n'
                                 '"Button","RLMOB-PNEXT","~OKCode","NEXT","1","9","","","","","","","","","F4 Nxt","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","RLMENU888-2","","RLMENU888-2","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTI2Nzk1LjAwMy4wMS4wMQ==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","1","0","","work.type.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PMLGF","~OKCode","/NEX","1","1","vreserve002.sign.off","","","","","","","correct.message","F8 LOff","","0","0","1","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PBACK","~OKCode","/EBACK","1","2","vcommand001.new.function","","","","","","","correct.message","F3 Back","","0","0","1","0","0","0","0","0","","0"\r\n'
                                 '"Button","TEXT1","~OKCode","1","1","3","","","","","","","","","1.picking.voc.menu                 ...","","0","0","0","0","0","1","0","0","","0"\r\n'
                                 '"Button","TEXT2","~OKCode","2","1","4","","","","","","","","","2.picking.voc.menu                 ...","","0","0","0","0","0","1","0","0","","0"\r\n'
                                 '"GetNumeric","RLMOB-MENOPT","rlmob-menopt[1]","","1","9","","","work.type.prompt","","","","","","","RLMOB-PNEXT","0","0","0","0","0","0","1","1","","0"\r\n'
                                 '"Button","RLMOB-PNEXT","~OKCode","NEXT","1","10","","","","","","","","","F4 Nxt","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","SAPLLMOB100","","SAPLLMOB100","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE2Mjk4LjAwNC4wMi4wMg==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PMLGF","~OKCode","/NEX","0","1","vreserve002.sign.off","","","","","","","correct.message","","","0","0","1","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","1","1","","transfer.order.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"GetBarCode","INP_100","inp_100[1]","","1","2","","","Transfer Order","","","","","","","RLMOB-PNEXT","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PBACK","~OKCode","/EBACK","1","6","vcommand009.new.work.type","","","","","","","correct.message","F3 Back","","0","0","1","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PNEXT","~OKCode","NEXT","1","7","","","","","","","","","F4 Nxt","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","SAPLLMOB212","","SAPLLMOB212","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE4NjQyLjAwNS4wMy4wNA==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP-GROUP-1","","","1","0","","say.ready.help.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-VLTYP","ltap-vltyp[1]","V W O ","1","1","","","storage.type.message","","","","","","","","0","0","0","1","1","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PBACK","~OKCode","/EBACK","1","2","vcommand018.back","","","","","","","","F3 Back","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","RLMOB-CLGPLA","rlmob-clgpla[1]","123","2","0","","speak.check.digits.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-VLPLA","ltap-vlpla[1]","V O 0 1 0 1 ","2","2","","","source.bin.message",",,","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","RLMOB-VSOLA","rlmob-vsola[1]","2","2","3","","","pick.message","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-ALTME","ltap-altme[1]","EA","2","4","","","",",,","","","","","","","0","0","0","1","0","0","0","0","","1"\r\n'
                                 '"GetBarCode","RLMOB-CLGPLA","rlmob-clgpla[1]","123","2","5","","","","","wrong.message","try.again.message","","","","RLMOB-PSAVE","1","0","0","0","0","0","3","3","","0"\r\n'
                                 '"Vocabulary","LTAP-MATNR","ltap-matnr[1]","VW_MAT3","2","6","vcommand002.material.number","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Vocabulary","RLMOB-MMAKT","rlmob-mmakt[1]","Material 3","2","7","vcommand003.material.description","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Vocabulary","LTAP-VLTYP","ltap-vltyp[1]","V W O ","2","8","vcommand021.storage.type","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PPGDN","~OKCode","PGDN","2","12","vcommand007.next.slot","","","","","","","","v","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PDETL","~OKCode","DETL","2","13","vcommand015.detail","","","","","","","","F5 Det","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PDIFF","~OKCode","DIFF","2","14","vcommand016.difference","","","","","","","","F6 Diff","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PSAVE","~OKCode","SAVE","2","15","","","","","","","","","F1 Save","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","SAPLLMOB212-1","","SAPLLMOB212-1","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE0NDY3LjAwNi4wMy4wNA==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","","","","1","1","","","","","","","","","","RLMOB-PPGDN","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PPGDN","~OKCode","PGDN","1","11","","","","","","","","","v","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","SAPLLMOB212","","SAPLLMOB212","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTI1NzcyLjAwNy4wMy4wNA==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP-GROUP-1","","","1","0","","say.ready.help.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-VLTYP","ltap-vltyp[1]","V W O ","1","1","","","storage.type.message","","","","","","","","0","0","0","1","1","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PBACK","~OKCode","/EBACK","1","2","vcommand018.back","","","","","","","","F3 Back","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","RLMOB-CLGPLA","rlmob-clgpla[1]","123","2","0","","speak.check.digits.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-VLPLA","ltap-vlpla[1]","V O 0 4 0 6 ","2","2","","","source.bin.message",",,","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","RLMOB-VSOLA","rlmob-vsola[1]","4","2","3","","","pick.message","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-ALTME","ltap-altme[1]","EA","2","4","","","",",,","","","","","","","0","0","0","1","0","0","0","0","","1"\r\n'
                                 '"GetBarCode","RLMOB-CLGPLA","rlmob-clgpla[1]","123","2","5","","","","","wrong.message","try.again.message","","","","RLMOB-PSAVE","1","0","0","0","0","0","3","3","","0"\r\n'
                                 '"Vocabulary","LTAP-MATNR","ltap-matnr[1]","VW_MAT4","2","6","vcommand002.material.number","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Vocabulary","RLMOB-MMAKT","rlmob-mmakt[1]","Material 4","2","7","vcommand003.material.description","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Vocabulary","LTAP-VLTYP","ltap-vltyp[1]","V W O ","2","8","vcommand021.storage.type","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PPGUP","~OKCode","PGUP","2","13","vcommand008.previous.slot","","","","","","","","^","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PDETL","~OKCode","DETL","2","13","vcommand015.detail","","","","","","","","F5 Det","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PDIFF","~OKCode","DIFF","2","14","vcommand016.difference","","","","","","","","F6 Diff","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PSAVE","~OKCode","SAVE","2","15","","","","","","","","","F1 Save","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","SAPLLMOB212-2","","SAPLLMOB212-2","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE0ODU1LjAwOC4wMy4wNA==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","","","","1","1","","","","","","","","","","RLMOB-PNEXT","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PNEXT","~OKCode","CMPL","1","2","","","","","","","","","F4 Nxt","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","SAPLLMOB312","","SAPLLMOB312","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE2MjMuMDA5LjA0LjA2====","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","1","0","","say.ready.help.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-NLTYP","ltap-nltyp[1]","916","1","1","","","destination.storage.type.message",",,","","","","","","RLMOB-PSAVE","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","LTAP-NLPLA","ltap-nlpla[1]","0080006512","1","2","","","destination.bin.message",",,","","","","","","RLMOB-PSAVE","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PSAVE","~OKCode","SAVE","1","5","vreserve001.ready","deliver.say.ready.message","","","","","","","F1 Save","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PBACK","~OKCode","/EBACK","1","6","vcommand018.back","","","","","","","","F3 Back","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PDIFF","~OKCode","DIFF","1","10","vcommand016.difference","","","","","","","","F6 Diff","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PDETL","~OKCode","DETL","1","11","vcommand015.detail","","","","","","","","F5 Det","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PPGDN","~OKCode","PGDN","1","13","vcommand007.next.slot","","","","","","","","v","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Vocabulary","LTAP-MATNR","ltap-matnr[1]","VW_MAT3","1","15","vcommand002.material.number","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '"Vocabulary","RLMOB-MMAKT","rlmob-mmakt[1]","Material 3","1","16","vcommand003.material.description","","","","","","","","","","0","0","0","1","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","SAPLLMOB100","","SAPLLMOB100","0","0","","http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTIzNjkyLjAxMC4wMi4wMg==","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PMLGF","~OKCode","/NEX","0","1","vreserve002.sign.off","","","","","","","correct.message","","","0","0","1","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","1","1","","transfer.order.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"GetBarCode","INP_100","inp_100[1]","","1","2","","","Transfer Order","","","","","","","RLMOB-PNEXT","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PBACK","~OKCode","/EBACK","1","6","vcommand009.new.work.type","","","","","","","correct.message","F3 Back","","0","0","1","0","0","0","0","0","","0"\r\n'
                                 '"Button","RLMOB-PNEXT","~OKCode","NEXT","1","7","","","","","","","","","F4 Nxt","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","ENDOFSESSION","","ENDOFSESSION","0","0","","http://10.201.94.23:8006/sap/vowm_lm01/","MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","ENDOFSESSION","","ENDOFSESSION","1","1","","","sign.off.message","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')
        self.set_server_response('"ScreenID","PT-INIT-Integrated","","PT-INIT-Integrated","0","0","","http://10.201.94.23:8006/sap/vowm_lm01/","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","1","0","","say.ready.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","WelcomePrompt","","","1","1","","","welcome.message","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SpeakPrompt","OperatorPrompt","",".operator","1","2","","","current.operator.message","continue.say.ready3.message","","","","","","","0","0","0","1","1","0","0","0","","0"\r\n'
                                 '"Help","HELP","","","2","0","","say.password.message","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"PassThrough","sap-user","sap-user",".operatorId","2","1","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"PassThrough","sap-client","sap-client","800","2","2","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"PassThrough","sap-language","sap-language",".languageCode","2","3","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"GetNumeric","sap-Password","sap-Password","","2","4","","","password.prompt","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '"SignOn","SignOn","","","2","5","","","","","","","","","","","0","0","0","0","0","0","0","0","","0"\r\n'
                                 '\n'
                                 '\n')

        #queue of Dialog Responses
        self.post_dialog_responses('VRESERVE001',  # Welcome to the Voice Direct ERP system. Current operator is Operator.Name , to continue, say ready.
                                   '123456!',      # Password?
                                   '2',            # Function?
                                   '1',            # Work type?
                                   '#11573',       # Transfer Order
                                   'VRESERVE001',  # storage type V W O
                                   '#123',         # source bin V O 0 1 0 1 ,, pick 2 eaches ,, 
                                   'VRESERVE001',  # storage type V W O
                                   '#123',         # source bin V O 0 4 0 6 ,, pick 4 eaches ,, 
                                   'VRESERVE001',  # destination,,, storage type 916 ,, bin 0080006512 ,, ,, to deliver, say ready
                                   'VRESERVE002',  # Transfer Order
                                   'VRESERVE003',  # VRESERVE002, correct?
                                   '-')            # Welcome to the Voice Direct ERP system. Current operator is Operator.Name , to continue, say ready.

        #run main application
        self.assertRaises(EndOfApplication, main)

        #validate prompts
        self.validate_prompts('Welcome to the Voice Direct ERP system. Current operator is Operator.Name , to continue, say ready.',
                              'Password?',
                              'Function?',
                              'Work type?',
                              'Transfer Order',
                              'storage type V W O',
                              'source bin V O 0 1 0 1 ,, pick 2 eaches ,, ',
                              'storage type V W O',
                              'source bin V O 0 4 0 6 ,, pick 4 eaches ,, ',
                              'destination,,, storage type 916 ,, bin 0080006512 ,, ,, to deliver, say ready',
                              'Transfer Order',
                              'VRESERVE002, correct?',
                              'Welcome to the Voice Direct ERP system. Current operator is Operator.Name , to continue, say ready.')

        #validate LUT Requests
        self.validate_server_requests(['"Init"', '"en_US"', '""', '""', '""', '""', '""', '""'],
                                      ['"SignOn"', '"en_US"', '"http://10.201.94.23:8006/sap/vowm_lm01/"', '""', '"sap-client"', '"800"', '"sap-user"', '"Operator.Id"', '"sap-Password"', '"123456"', '"sap-language"', '"EN"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTI4MDE3LjAwMi4wMS4wMQ=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"~OKCode"', '"NEXT"', '"rlmob-menopt[1]"', '"2"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTI2Nzk1LjAwMy4wMS4wMQ=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"~OKCode"', '"NEXT"', '"rlmob-menopt[1]"', '"1"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE2Mjk4LjAwNC4wMi4wMg=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"~OKCode"', '"NEXT"', '"inp_100[1]"', '"11573"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE4NjQyLjAwNS4wMy4wNA=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"rlmob-clgpla[1]"', '"123"', '"~OKCode"', '"SAVE"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE0NDY3LjAwNi4wMy4wNA=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"~OKCode"', '"PGDN"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTI1NzcyLjAwNy4wMy4wNA=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"rlmob-clgpla[1]"', '"123"', '"~OKCode"', '"SAVE"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE0ODU1LjAwOC4wMy4wNA=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"~OKCode"', '"CMPL"'],
                                      ['"Post"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTE2MjMuMDA5LjA0LjA2===="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"~OKCode"', '"SAVE"'],
                                      ['"SignOff"', '"en_US"', '"http://10.201.94.23:8006/sap(cz1TSUQlM2FBTk9OJTNhc3FhLXNhcC1idWlsZF9FQzFfMDYlM2FxR2h2Y1RFMmhmQTV4MEZ2X2lUcXRxOVlVLXNoR0tqVzRvZVU2eWpNLUFUVA==)/vowm_lm01/~flNUQVRFPTIzNjkyLjAxMC4wMi4wMg=="', '"MYSAPSSO2=AjQxMDMBABhCAEsAUgBJAEwARQBZACAAIAAgACAAIAACAAY4ADAAMAADABBFAEMAMQAgACAAIAAgACAABAAYMgAwADEAMwAwADUAMgAwADIAMAAxADcABQAEAAAACAYAAlgACQACRQD%2fBFowggRWBgkqhkiG9w0BBwKgggRHMIIEQwIBATELMAkGBSsOAwIaBQAwCwYJKoZIhvcNAQcBoIIDADCCAvwwggK8AgcgEAkSFDVFMAkGByqGSM44BAMwZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzEwHhcNMTAwOTEyMTQzNTQ1WhcNMzgwMTAxMDAwMDAxWjBkMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTETMBEGA1UECxMKU0FQIFdlYiBBUzEUMBIGA1UECxMLSTAwMjAyODM4NTYxDDAKBgNVBAMTA0VDMTCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD%2f6eQGsMlhI8fQZZ6GQkguFSNotRik06FKV4InHUw3roCakhJ%21LmLRxgUXuXBSIxAwIWvXRFuK9tp52poc7q5bsiJjuoFe%2fvqdPb%2f5oo4HysjhsjCE%217ZfDur3%2fnuaj0EOtuSKXOv%2fEUELpiPfWiRpvVW5IPImh74uBr95ZP%21mBwIVALxH%2190makesaXYZx72OSweE1fF9AoGBAI1aSPQVeriCfhTmGUWXlx5i1ScIc9MqWlqLArugh5mlKGPV9mYlKfVy6g0rXP3Ck5y2zRafe6MHfqCvJeLaXAYvUzTICwsFkz5hBhEg1s8oKe9B5BxMdcPuSz%21v05GA3Z7CUHK07uVcFNcKz4cnvcjGwvhqeeW%2fqdLEty6VTDnMA4GFAAKBgQCqWYv1L0Y5JM9eyPU17jLmZETNNTWLRpQeL9tg4V8I4FJrYUhP%21BQzE3zylMDY63oXPd45PryiNRklHo2gTaZ6CIbyoztmbspLx8MUUFTOLOTMRdzg0ausEeUDS%2f3nMAnd7UrjBvb9JsTi5c3q74sk545%2fUmzknFJKSprVyKvJjTAJBgcqhkjOOAQDAy8AMCwCFFeeFWV6Jq0bxmoH9dhwKHUN8CLzAhQCY5gFGQH%21oGSrs74gsgfPwByTyzGCAR4wggEaAgEBMG8wZDELMAkGA1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxEzARBgNVBAsTClNBUCBXZWIgQVMxFDASBgNVBAsTC0kwMDIwMjgzODU2MQwwCgYDVQQDEwNFQzECByAQCRIUNUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTEzMDUyMDIwMTczOVowIwYJKoZIhvcNAQkEMRYEFHAzFB203AQvgbmEazOgUpoSyf4xMAkGByqGSM44BAMELzAtAhRMoNuzs9Mtrw6GNX%2fkE15EgIXIiAIVAJc%2fvg2ekRz2M3O3xTfbhYsM3rsI; path=/; domain=.201.94.23"', '"~OKCode"', '"/NEX"'],
                                      ['"Init"', '"en_US"', '""', '""', '""', '""', '""', '""'])

        #validate log messages

if __name__ == '__main__':
    unittest.main()
